service: AuthAPI
frameworkVersion: '2'
configValidationMode: error
unresolvedVariablesNotificationMode: error
deprecationNotificationMode: error

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage}
  region: eu-central-1
  stackName: AuthAPI
  memorySize: 1024
  timeout: 10
  logRetentionInDays: 14
  deploymentPrefix: serverless
  versionFunctions: false
  environment:
    ENVIRONMENT: ${opt:stage}
    endpointType: regional
  iam:
    role: AuthAPILambdaRole

package:
  individually: true
  excludeDevDependencies: false

resources:
  - ${file(./iam.yml)}

functions:
  Register:
    handler: bin/func_register
    name: AuthAPI-Register
    package:
      patterns:
        - '!./**'
        - ./bin/func_register
    events:
      - httpApi:
          path: /auth/register
          method: POST
  Login:
    handler: bin/func_login
    name: AuthAPI-Login
    package:
      patterns:
        - '!./**'
        - ./bin/func_login
    events:
      - httpApi:
          path: /auth/login
          method: POST