Resources:
  BookAPILambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: BookAPI
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: BookAPIPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - arn:aws:dynamodb:eu-central-1:685079929070:table/zula_books
                  - arn:aws:dynamodb:eu-central-1:685079929070:table/zula_sessions
                  - arn:aws:dynamodb:eu-central-1:685079929070:table/zula_users
                  - arn:aws:dynamodb:eu-central-1:685079929070:table/zula_translations
                  - arn:aws:dynamodb:eu-central-1:685079929070:table/zula_pages
                  - arn:aws:dynamodb:eu-central-1:685079929070:table/zula_translations/index/book_id-index
                  - arn:aws:dynamodb:eu-central-1:685079929070:table/zula_pages/index/translation_id-index